# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deepseekcode < Formula
  desc "Terminal-native coding agent for DeepSeek models."
  homepage "https://github.com/amemiya02/deepseekcode"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amemiya02/deepseekcode/releases/download/v0.3.7/deepseekcode_0.3.7_darwin_amd64.tar.gz"
      sha256 "80c015b1f222bd4bf87d2a13f05a8c7584a92c81bbae56f824c7fb88f4af6f33"

      define_method(:install) do
        bin.install "dsc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amemiya02/deepseekcode/releases/download/v0.3.7/deepseekcode_0.3.7_darwin_arm64.tar.gz"
      sha256 "e6e4c85b2cd7a40703992841f8c19dbbcb996f7be22a58cd676c667ee2232487"

      define_method(:install) do
        bin.install "dsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amemiya02/deepseekcode/releases/download/v0.3.7/deepseekcode_0.3.7_linux_amd64.tar.gz"
      sha256 "2539ca88f3e1a436641f3f47afc4d7cc32f1c7d5d9108deb523006c900ce9ac0"
      define_method(:install) do
        bin.install "dsc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amemiya02/deepseekcode/releases/download/v0.3.7/deepseekcode_0.3.7_linux_arm64.tar.gz"
      sha256 "611d8bc016a6bb1d9a6a3700f8ab8d3ce442d018a4c2cb90887fdb5ff827a5b4"
      define_method(:install) do
        bin.install "dsc"
      end
    end
  end

  test do
    system "#{bin}/dsc -version"
  end
end
